deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
  branchDependency:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    depends_on:
      - child-deploymentB/branch
